#!/usr/bin/env python3
"""
Secure Environment Setup for PureProtX
Helps you configure the .env file safely
"""

import os
import getpass
from pathlib import Path

def setup_environment():
    """Interactive setup for PureProtX environment."""
    print("🔐 PureProtX Secure Environment Setup")
    print("=" * 50)
    
    env_file = Path(".env")
    env_example = Path(".env.example")
    
    if env_file.exists():
        print(f"⚠ .env file already exists!")
        overwrite = input("Do you want to overwrite it? (y/N): ").lower().strip()
        if overwrite != 'y':
            print("Setup cancelled.")
            return
    
    print("\n📋 Please provide the following information:")
    print("(Press Enter to skip optional fields)")
    
    # Get private key securely
    print("\n🔑 Purechain Private Key:")
    print("   This is required for blockchain operations.")
    print("   Get this from your Purechain wallet.")
    print("   ⚠ NEVER share this key with anyone!")
    
    while True:
        private_key = getpass.getpass("   Enter your private key (hidden input): ").strip()
        if private_key:
            # Remove 0x prefix if present
            if private_key.startswith('0x'):
                private_key = private_key[2:]
            
            # Basic validation (64 hex characters)
            if len(private_key) == 64 and all(c in '0123456789abcdefABCDEF' for c in private_key):
                break
            else:
                print("   ❌ Invalid private key format. Should be 64 hex characters.")
        else:
            print("   ❌ Private key is required for blockchain operations.")
    
    # Optional settings
    print("\n⚙ Optional Settings:")
    
    rpc_url = input("   Custom RPC URL (default: https://purechainnode.com:8547): ").strip()
    if not rpc_url:
        rpc_url = "https://purechainnode.com:8547"
    
    contract_address = input("   Custom contract address (optional): ").strip()
    
    network = input("   Network (testnet/mainnet, default: testnet): ").strip()
    if not network:
        network = "testnet"
    
    debug = input("   Enable debug mode? (y/N): ").lower().strip() == 'y'
    
    # Create .env file
    env_content = f"""# PureProtX Environment Configuration
# Generated by setup_env.py
# NEVER commit this file to git!

# Purechain Configuration
TEST_PRIVATE_KEY={private_key}
PURECHAIN_RPC_URL={rpc_url}
NETWORK={network}

# Optional Settings
"""
    
    if contract_address:
        env_content += f"CONTRACT_ADDRESS={contract_address}\n"
    
    env_content += f"DEBUG={'true' if debug else 'false'}\n"
    
    # Write .env file
    with open(env_file, 'w') as f:
        f.write(env_content)
    
    # Set secure permissions (Unix-like systems)
    try:
        os.chmod(env_file, 0o600)  # Read/write for owner only
    except:
        pass  # Windows doesn't support chmod
    
    print("\n✅ Environment setup complete!")
    print(f"   .env file created: {env_file.absolute()}")
    print("   🔒 File permissions set to owner-only")
    print("\n🚨 SECURITY REMINDERS:")
    print("   • .env file is already in .gitignore")
    print("   • NEVER commit .env to version control")
    print("   • NEVER share your private key")
    print("   • Keep your .env file secure")
    
    # Test the configuration
    print("\n🧪 Testing configuration...")
    try:
        from dotenv import load_dotenv
        load_dotenv()
        
        test_key = os.getenv("TEST_PRIVATE_KEY")
        test_rpc = os.getenv("PURECHAIN_RPC_URL")
        
        if test_key and test_rpc:
            print("   ✅ Configuration loaded successfully")
            print(f"   ✅ RPC URL: {test_rpc}")
            print(f"   ✅ Private key: {'*' * 60}...{test_key[-4:]}")
        else:
            print("   ❌ Configuration test failed")
            
    except ImportError:
        print("   ⚠ python-dotenv not installed, skipping test")
    except Exception as e:
        print(f"   ❌ Configuration test failed: {e}")

def main():
    """Main function."""
    try:
        setup_environment()
    except KeyboardInterrupt:
        print("\n\nSetup cancelled by user.")
    except Exception as e:
        print(f"\n❌ Setup failed: {e}")

if __name__ == "__main__":
    main()
